exclude:
  - CNAME
  - LICENSE
  - "README*"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      style: "style"

plugins:
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings

optional_front_matter:
  remove_originals: true
